# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackMaterialValueList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackMaterialValueList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackMaterialValueList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackMaterialValueList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackMaterialValueList
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Titan.Animation.TrackMaterialValue import TrackMaterialValue
            obj = TrackMaterialValue()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackMaterialValueList
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackMaterialValueList
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TrackMaterialValueListStart(builder):
    builder.StartObject(1)

def Start(builder):
    TrackMaterialValueListStart(builder)

def TrackMaterialValueListAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def AddValues(builder, values):
    TrackMaterialValueListAddValues(builder, values)

def TrackMaterialValueListStartValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartValuesVector(builder, numElems: int) -> int:
    return TrackMaterialValueListStartValuesVector(builder, numElems)

def TrackMaterialValueListEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackMaterialValueListEnd(builder)
