# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Animation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackFlag_Bool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackFlag_Bool()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackFlag_Bool(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackFlag_Bool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackFlag_Bool
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TrackFlag_BoolStart(builder):
    builder.StartObject(1)

def Start(builder):
    TrackFlag_BoolStart(builder)

def TrackFlag_BoolAddValue(builder, value):
    builder.PrependBoolSlot(0, value, 0)

def AddValue(builder, value):
    TrackFlag_BoolAddValue(builder, value)

def TrackFlag_BoolEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackFlag_BoolEnd(builder)
